### ISSUE TITLE
Add support to SQLCipher

### ISSUE THREAD

**Issue by ofrankmartin** [jlaine/qdjango#16]
As SQLCipher behave just like an SQLite database and it is possible to create a Qt plugin to use it, I think the only change needed to get support to it is to add it on the list of possible drivers on QDjango::setDatabase(QSqlDatabase). Something like:
<code>
(...) && database.driverName() != QLatin1String("QSQLCIPHER"))
</code>
I tested it and the only "issue" is the warning, everything else works like a charm.
Here is the SQLCipher Qt Plugin project:

https://github.com/sijk/qt5-sqlcipher

**Comment by ericLemanissier** [comment]
sqlcipher is actually maintained: https://github.com/sqlcipher/sqlcipher
We have been using it for years in our qt project, by compiling qsqlcipher plugin by hand, because it does not seem there is a reference open source version available. It would be a good point that qdjango handles QSQLCIPHER by considering it is identical to SQLite
